---
title: Projects
---


<div class="container">

  <!-- Project 1 (panel left, text right) -->
<div class="row project-row">
<div class="col-sm-6">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Master's Thesis</h3>
</div>
<div class="panel-body">
<p><a href="https://etd.library.emory.edu/concern/etds/xd07gv41j?locale=en">Community Assets Rooted in Place: Associations Between Local Food Systems and Food Insecurity in Metro Atlanta</a></p>
<p><a href="https://s-charlo.github.io/thesis_dashboard/">Interactive infographic for the thesis</a></p>
</div>
</div>
</div>

<div class="col-sm-6">
<div class="project-description">
<p>
This project examines the relationship between food insecurity and the
spatial distribution of local food system components using statistical analysis and thematic mapping in R.
</p>
</div>
</div>
</div>

  <!-- Project 2 (text left, panel right) -->
<div class="row project-row">
<div class="col-sm-6">
<div class="project-description">
<p>
This project explores the relationship between chronic illness multimorbidity and long-term COVID effects within adults in the United States using statistical analysis in SAS.
</p>
</div>
</div>

<div class="col-sm-6">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Post Board Presentation</h3>
</div>
<div class="panel-body">
<p><a href="files/poster_board.pdf">Persistent Predictors and Persistent COVID: An analysis of Long-term COVID Effects, Chronic Health Conditions, and Sociodemographic Characteristics of US Adults</a></p>
</div>
</div>
</div>
</div>

  <!-- Project 3 (panel left again) -->
<div class="row project-row">
<div class="col-sm-6">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Post Board Presentation</h3>
</div>
<div class="panel-body">
<p><a href="files/python_board.pdf">An Exploratory Analysis of Food Insecurity and Associated Factors in Metro Atlanta</a></p>
</div>
</div>
</div>

<div class="col-sm-6">
<div class="project-description">
<p>
This project is an exploratory analysis of the factors associated with food insecurity using statistical analysis and thematic mapping in Python.
</p>
</div>
</div>
</div>

  <!-- Project 4 (text left again) -->
<div class="row project-row">
<div class="col-sm-6">
<div class="project-description">
<p>
This project is a conceptual model of constructs from various public health theories/frameworks across each level of the Social Ecological Model. It demonstrates a conceptual rationale for the desired outcome of the health-seeking behavior of accessing doula care.
</p>
</div>
</div>

<div class="col-sm-6">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Conceptual Map Construction</h3>
</div>
<div class="panel-body">
<p><a href="files/concept_map.pdf">Doula Care: Addressing the Black Maternal Mortality Crisis in Georgia</a></p>
</div>
</div>
</div>
</div>

</div>

